spring:
  profiles:
    active: docker
---
spring:
  profiles:
    name: cloud
  cloud:
    config:
      discovery:
        enabled: true
      server:
        git:
          uri: https://github.com/colin-icontrol/configuration
        health:
          repositories:
            alarmservice:
              label: master
              profiles: docker
            discovery:
              label: docker
              profiles: docker
server:
  port: 8888
info:
  description: Config Server
  url: https://github.com/colin-icontrol/alarmcomposition
---
spring:
  application:
    name: configserver
  profiles:
    name: docker
  cloud:
    config:
      discovery:
        enabled: true
      server:
        git:
          uri: https://github.com/colin-icontrol/configuration
        health:
          repositories:
            alarmservice:
              label: master
              profiles: docker
            discovery:
              label: master
              profiles: docker
server:
  port: 8888
info:
  description: Config Server
  url: https://github.com/colin-icontrol/alarmcomposition